### ISSUE TITLE
Allow of block types in mining sources

### ISSUE THREAD

**Issue by Elikill58** [Archy-X/AureliumSkills#118]
### Feature description

Instead of direct enum like [MiningSource](https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/skills/mining/MiningSource.java), allow all types to be able to use like:
```yml
  mining:
    stone: 0.2
    oak_log: 1
    my_amazing_type: 0.5
```
