### ISSUE TITLE
Wearing armor with enchanted by AdvancedEnchantments will sometimes modify attributes

### ISSUE THREAD

**Issue by Nanpure** [Archy-X/AureliumSkills#241]
### Server software and version

Papr 1.20.4

### Expected behavior

Wearing armor should no modify attributes.

### Actual behavior

Attributes are modified by armor.

### How to reproduce

Boots with AdvancedEnchantments will sometimes add random modifications to attributes (some positive some negative).

### Additional information

I have several boots enchanted by AdvancedEnchantments. They have a lot of enchantments and some lore but do not have any armor modifiers (as tested with "/sk armor modifier list").

I have made a video to demonstrate the problem:

https://www.youtube.com/watch?v=9CHXc7Um4pQ

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Nanpure** [comment]
I made a new video after isolating the effect of reducing wisdom. I don't know yet why the other piece of armor is increasing wisdom. Adding either Springs III or Gears III reduces wisdom by 11.

Here is another video:

https://www.youtube.com/watch?v=yVn0QQvkTRo

Here are the enchantments and their effects:

```
springs:
  display: '%group-color%Springs'
  description: Jump boost.
  applies-to: Boots
  type: EFFECT_STATIC
  group: RARE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:JUMP:0
    '2':
      effects:
      - POTION:JUMP:1
    '3':
      effects:
      - POTION:JUMP:2
gears:
  display: '%group-color%Gears'
  description: Zoom zoom.
  applies-to: Boots
  type: EFFECT_STATIC
  group: EXOTIC
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:0
    '2':
      effects:
      - POTION:SPEED:1
    '3':
      effects:
      - POTION:SPEED:2
```
